<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>grpc_ros_adapter</name>
  <version>0.1.0</version>
  <description>
	  The package provides a ROS to GRPC bridge.
  </description>

  <maintainer email="labust@fer.hr">LABUST</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>builtin_interfaces</depend>
  <depend>geometry_msgs</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>rclpy</depend>
  <depend>rosgraph_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2_msgs</depend>
  <depend>visualization_msgs</depend>

  <exec_depend>auv_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>labust_msgs</exec_depend>
  <exec_depend>python3-grpcio</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-protobuf</exec_depend>
  <exec_depend>python3-rospkg</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>underwater_msgs</exec_depend>
  <exec_depend>uuv_sensor_msgs</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
   <build_type>ament_python</build_type>
  </export>
</package>
