# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import navigation_pb2 as navigation__pb2


class NavigationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendNavigationMessage = channel.unary_unary(
                '/navigation.Navigation/SendNavigationMessage',
                request_serializer=navigation__pb2.NavigationRequest.SerializeToString,
                response_deserializer=navigation__pb2.NavigationResponse.FromString,
                )


class NavigationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendNavigationMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NavigationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendNavigationMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNavigationMessage,
                    request_deserializer=navigation__pb2.NavigationRequest.FromString,
                    response_serializer=navigation__pb2.NavigationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'navigation.Navigation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Navigation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendNavigationMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/navigation.Navigation/SendNavigationMessage',
            navigation__pb2.NavigationRequest.SerializeToString,
            navigation__pb2.NavigationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
