# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: navigation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2

from common_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='navigation.proto',
  package='navigation',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.navigationB\nNavigationP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10navigation.proto\x12\nnavigation\x1a\x0c\x63ommon.proto\"\xc2\x01\n\x11NavigationRequest\x12\x11\n\ttimeStamp\x18\x01 \x01(\x01\x12!\n\x08position\x18\x02 \x01(\x0b\x32\x0f.common.Vector3\x12$\n\x0borientation\x18\x03 \x01(\x0b\x32\x0f.common.Vector3\x12\'\n\x0elinearVelocity\x18\x04 \x01(\x0b\x32\x0f.common.Vector3\x12(\n\x0f\x61ngularVelocity\x18\x05 \x01(\x0b\x32\x0f.common.Vector3\"%\n\x12NavigationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x66\n\nNavigation\x12X\n\x15SendNavigationMessage\x12\x1d.navigation.NavigationRequest\x1a\x1e.navigation.NavigationResponse\"\x00\x42\x31\n\x1bio.grpc.examples.navigationB\nNavigationP\x01\xa2\x02\x03HLWP\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,],
  public_dependencies=[common__pb2.DESCRIPTOR,])




_NAVIGATIONREQUEST = _descriptor.Descriptor(
  name='NavigationRequest',
  full_name='navigation.NavigationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeStamp', full_name='navigation.NavigationRequest.timeStamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='navigation.NavigationRequest.position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='navigation.NavigationRequest.orientation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='linearVelocity', full_name='navigation.NavigationRequest.linearVelocity', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angularVelocity', full_name='navigation.NavigationRequest.angularVelocity', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=241,
)


_NAVIGATIONRESPONSE = _descriptor.Descriptor(
  name='NavigationResponse',
  full_name='navigation.NavigationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='navigation.NavigationResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=280,
)

_NAVIGATIONREQUEST.fields_by_name['position'].message_type = common__pb2._VECTOR3
_NAVIGATIONREQUEST.fields_by_name['orientation'].message_type = common__pb2._VECTOR3
_NAVIGATIONREQUEST.fields_by_name['linearVelocity'].message_type = common__pb2._VECTOR3
_NAVIGATIONREQUEST.fields_by_name['angularVelocity'].message_type = common__pb2._VECTOR3
DESCRIPTOR.message_types_by_name['NavigationRequest'] = _NAVIGATIONREQUEST
DESCRIPTOR.message_types_by_name['NavigationResponse'] = _NAVIGATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NavigationRequest = _reflection.GeneratedProtocolMessageType('NavigationRequest', (_message.Message,), {
  'DESCRIPTOR' : _NAVIGATIONREQUEST,
  '__module__' : 'navigation_pb2'
  # @@protoc_insertion_point(class_scope:navigation.NavigationRequest)
  })
_sym_db.RegisterMessage(NavigationRequest)

NavigationResponse = _reflection.GeneratedProtocolMessageType('NavigationResponse', (_message.Message,), {
  'DESCRIPTOR' : _NAVIGATIONRESPONSE,
  '__module__' : 'navigation_pb2'
  # @@protoc_insertion_point(class_scope:navigation.NavigationResponse)
  })
_sym_db.RegisterMessage(NavigationResponse)


DESCRIPTOR._options = None

_NAVIGATION = _descriptor.ServiceDescriptor(
  name='Navigation',
  full_name='navigation.Navigation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=282,
  serialized_end=384,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendNavigationMessage',
    full_name='navigation.Navigation.SendNavigationMessage',
    index=0,
    containing_service=None,
    input_type=_NAVIGATIONREQUEST,
    output_type=_NAVIGATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NAVIGATION)

DESCRIPTOR.services_by_name['Navigation'] = _NAVIGATION

# @@protoc_insertion_point(module_scope)
