# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_pb2 as common__pb2
import parameter_server_pb2 as parameter__server__pb2


class ParameterServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetParameter = channel.unary_unary(
                '/parameterserver.ParameterServer/GetParameter',
                request_serializer=parameter__server__pb2.GetParamRequest.SerializeToString,
                response_deserializer=parameter__server__pb2.ParamValue.FromString,
                )
        self.SetParameter = channel.unary_unary(
                '/parameterserver.ParameterServer/SetParameter',
                request_serializer=parameter__server__pb2.SetParamRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                )


class ParameterServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetParameter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParameterServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParameter,
                    request_deserializer=parameter__server__pb2.GetParamRequest.FromString,
                    response_serializer=parameter__server__pb2.ParamValue.SerializeToString,
            ),
            'SetParameter': grpc.unary_unary_rpc_method_handler(
                    servicer.SetParameter,
                    request_deserializer=parameter__server__pb2.SetParamRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parameterserver.ParameterServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ParameterServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/parameterserver.ParameterServer/GetParameter',
            parameter__server__pb2.GetParamRequest.SerializeToString,
            parameter__server__pb2.ParamValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetParameter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/parameterserver.ParameterServer/SetParameter',
            parameter__server__pb2.SetParamRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
