# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ping.proto',
  package='ping',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nping.proto\x12\x04ping\"\x18\n\x07PingMsg\x12\r\n\x05value\x18\x01 \x01(\x05\x32.\n\x04Ping\x12&\n\x04Ping\x12\r.ping.PingMsg\x1a\r.ping.PingMsg\"\x00\x62\x06proto3'
)




_PINGMSG = _descriptor.Descriptor(
  name='PingMsg',
  full_name='ping.PingMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ping.PingMsg.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=44,
)

DESCRIPTOR.message_types_by_name['PingMsg'] = _PINGMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PingMsg = _reflection.GeneratedProtocolMessageType('PingMsg', (_message.Message,), {
  'DESCRIPTOR' : _PINGMSG,
  '__module__' : 'ping_pb2'
  # @@protoc_insertion_point(class_scope:ping.PingMsg)
  })
_sym_db.RegisterMessage(PingMsg)



_PING = _descriptor.ServiceDescriptor(
  name='Ping',
  full_name='ping.Ping',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=46,
  serialized_end=92,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='ping.Ping.Ping',
    index=0,
    containing_service=None,
    input_type=_PINGMSG,
    output_type=_PINGMSG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PING)

DESCRIPTOR.services_by_name['Ping'] = _PING

# @@protoc_insertion_point(module_scope)
