# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sensor_streaming_pb2 as sensor__streaming__pb2


class SensorStreamingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamCameraSensor = channel.unary_unary(
                '/sensorstreaming.SensorStreaming/StreamCameraSensor',
                request_serializer=sensor__streaming__pb2.CameraStreamingRequest.SerializeToString,
                response_deserializer=sensor__streaming__pb2.CameraStreamingResponse.FromString,
                )
        self.StreamLidarSensor = channel.unary_unary(
                '/sensorstreaming.SensorStreaming/StreamLidarSensor',
                request_serializer=sensor__streaming__pb2.LidarStreamingRequest.SerializeToString,
                response_deserializer=sensor__streaming__pb2.LidarStreamingResponse.FromString,
                )
        self.StreamRadarSensor = channel.unary_unary(
                '/sensorstreaming.SensorStreaming/StreamRadarSensor',
                request_serializer=sensor__streaming__pb2.RadarStreamingRequest.SerializeToString,
                response_deserializer=sensor__streaming__pb2.RadarStreamingResponse.FromString,
                )


class SensorStreamingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamCameraSensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLidarSensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRadarSensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorStreamingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamCameraSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.StreamCameraSensor,
                    request_deserializer=sensor__streaming__pb2.CameraStreamingRequest.FromString,
                    response_serializer=sensor__streaming__pb2.CameraStreamingResponse.SerializeToString,
            ),
            'StreamLidarSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.StreamLidarSensor,
                    request_deserializer=sensor__streaming__pb2.LidarStreamingRequest.FromString,
                    response_serializer=sensor__streaming__pb2.LidarStreamingResponse.SerializeToString,
            ),
            'StreamRadarSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.StreamRadarSensor,
                    request_deserializer=sensor__streaming__pb2.RadarStreamingRequest.FromString,
                    response_serializer=sensor__streaming__pb2.RadarStreamingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sensorstreaming.SensorStreaming', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SensorStreaming(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamCameraSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sensorstreaming.SensorStreaming/StreamCameraSensor',
            sensor__streaming__pb2.CameraStreamingRequest.SerializeToString,
            sensor__streaming__pb2.CameraStreamingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamLidarSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sensorstreaming.SensorStreaming/StreamLidarSensor',
            sensor__streaming__pb2.LidarStreamingRequest.SerializeToString,
            sensor__streaming__pb2.LidarStreamingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamRadarSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sensorstreaming.SensorStreaming/StreamRadarSensor',
            sensor__streaming__pb2.RadarStreamingRequest.SerializeToString,
            sensor__streaming__pb2.RadarStreamingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
