# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import simulation_control_pb2 as simulation__control__pb2


class SimulationControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Step = channel.unary_unary(
                '/simulatoncontrol.SimulationControl/Step',
                request_serializer=simulation__control__pb2.StepRequest.SerializeToString,
                response_deserializer=simulation__control__pb2.StepResponse.FromString,
                )
        self.SetStartTime = channel.unary_unary(
                '/simulatoncontrol.SimulationControl/SetStartTime',
                request_serializer=simulation__control__pb2.SetStartTimeRequest.SerializeToString,
                response_deserializer=simulation__control__pb2.SetStartTimeResponse.FromString,
                )


class SimulationControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStartTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=simulation__control__pb2.StepRequest.FromString,
                    response_serializer=simulation__control__pb2.StepResponse.SerializeToString,
            ),
            'SetStartTime': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStartTime,
                    request_deserializer=simulation__control__pb2.SetStartTimeRequest.FromString,
                    response_serializer=simulation__control__pb2.SetStartTimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simulatoncontrol.SimulationControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimulationControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simulatoncontrol.SimulationControl/Step',
            simulation__control__pb2.StepRequest.SerializeToString,
            simulation__control__pb2.StepResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetStartTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simulatoncontrol.SimulationControl/SetStartTime',
            simulation__control__pb2.SetStartTimeRequest.SerializeToString,
            simulation__control__pb2.SetStartTimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
