# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tf.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tf.proto',
  package='tf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08tf.proto\x12\x02tf\x1a\x0c\x63ommon.proto\"7\n\x0eTfFrameRequest\x12\x0f\n\x07\x66rameId\x18\x01 \x01(\t\x12\x14\n\x0c\x63hildFrameId\x18\x02 \x01(\t\"|\n\x07TfFrame\x12\x0f\n\x07\x66rameId\x18\x01 \x01(\t\x12\x14\n\x0c\x63hildFrameId\x18\x02 \x01(\t\x12$\n\x0btranslation\x18\x03 \x01(\x0b\x32\x0f.common.Vector3\x12$\n\x08rotation\x18\x04 \x01(\x0b\x32\x12.common.Quaternion\"*\n\x0bTfFrameList\x12\x1b\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x0b.tf.TfFrame2\xd0\x01\n\x02Tf\x12\x30\n\x0cGetAllFrames\x12\r.common.Empty\x1a\x0f.tf.TfFrameList\"\x00\x12-\n\x08GetFrame\x12\x12.tf.TfFrameRequest\x1a\x0b.tf.TfFrame\"\x00\x12\x35\n\x0fStreamAllFrames\x12\r.common.Empty\x1a\x0f.tf.TfFrameList\"\x00\x30\x01\x12\x32\n\x0bStreamFrame\x12\x12.tf.TfFrameRequest\x1a\x0b.tf.TfFrame\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_TFFRAMEREQUEST = _descriptor.Descriptor(
  name='TfFrameRequest',
  full_name='tf.TfFrameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frameId', full_name='tf.TfFrameRequest.frameId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='childFrameId', full_name='tf.TfFrameRequest.childFrameId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=85,
)


_TFFRAME = _descriptor.Descriptor(
  name='TfFrame',
  full_name='tf.TfFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frameId', full_name='tf.TfFrame.frameId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='childFrameId', full_name='tf.TfFrame.childFrameId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='translation', full_name='tf.TfFrame.translation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='tf.TfFrame.rotation', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=211,
)


_TFFRAMELIST = _descriptor.Descriptor(
  name='TfFrameList',
  full_name='tf.TfFrameList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frames', full_name='tf.TfFrameList.frames', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=255,
)

_TFFRAME.fields_by_name['translation'].message_type = common__pb2._VECTOR3
_TFFRAME.fields_by_name['rotation'].message_type = common__pb2._QUATERNION
_TFFRAMELIST.fields_by_name['frames'].message_type = _TFFRAME
DESCRIPTOR.message_types_by_name['TfFrameRequest'] = _TFFRAMEREQUEST
DESCRIPTOR.message_types_by_name['TfFrame'] = _TFFRAME
DESCRIPTOR.message_types_by_name['TfFrameList'] = _TFFRAMELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TfFrameRequest = _reflection.GeneratedProtocolMessageType('TfFrameRequest', (_message.Message,), {
  'DESCRIPTOR' : _TFFRAMEREQUEST,
  '__module__' : 'tf_pb2'
  # @@protoc_insertion_point(class_scope:tf.TfFrameRequest)
  })
_sym_db.RegisterMessage(TfFrameRequest)

TfFrame = _reflection.GeneratedProtocolMessageType('TfFrame', (_message.Message,), {
  'DESCRIPTOR' : _TFFRAME,
  '__module__' : 'tf_pb2'
  # @@protoc_insertion_point(class_scope:tf.TfFrame)
  })
_sym_db.RegisterMessage(TfFrame)

TfFrameList = _reflection.GeneratedProtocolMessageType('TfFrameList', (_message.Message,), {
  'DESCRIPTOR' : _TFFRAMELIST,
  '__module__' : 'tf_pb2'
  # @@protoc_insertion_point(class_scope:tf.TfFrameList)
  })
_sym_db.RegisterMessage(TfFrameList)



_TF = _descriptor.ServiceDescriptor(
  name='Tf',
  full_name='tf.Tf',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=258,
  serialized_end=466,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAllFrames',
    full_name='tf.Tf.GetAllFrames',
    index=0,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=_TFFRAMELIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFrame',
    full_name='tf.Tf.GetFrame',
    index=1,
    containing_service=None,
    input_type=_TFFRAMEREQUEST,
    output_type=_TFFRAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamAllFrames',
    full_name='tf.Tf.StreamAllFrames',
    index=2,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=_TFFRAMELIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamFrame',
    full_name='tf.Tf.StreamFrame',
    index=3,
    containing_service=None,
    input_type=_TFFRAMEREQUEST,
    output_type=_TFFRAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TF)

DESCRIPTOR.services_by_name['Tf'] = _TF

# @@protoc_insertion_point(module_scope)
